name: Add External EXE to Release

on:
  push:
    tags:
      - 'v*'

jobs:
  add-exe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5          # از v4 به v5 تغییر یافته است

      - name: Download EXE from source project's release
        env:
          DOWNLOAD_URL: "https://github.com/Danialsamadi/cf-knife/releases/download/v1.4.1/cf-knife-windows-amd64.exe"
        run: |
          curl -L -o application.exe "$DOWNLOAD_URL"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v3   # از v1 به v3 تغییر یافته است
        with:
          files: application.exe
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
