name: Add External EXE to Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  add-exe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (with full history and fetch depth)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main   # مستقیماً شاخه main را checkout کن

      - name: Download EXE
        env:
          DOWNLOAD_URL: "https://github.com/Danialsamadi/cf-knife/releases/download/v1.4.1/cf-knife-windows-amd64.exe"
        run: |
          curl -L -o application.exe "$DOWNLOAD_URL"

      - name: Commit and push EXE to repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add application.exe
          git commit -m "Add EXE file automatically from workflow" || echo "No changes to commit"
          git push origin main
